# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RevealAnimation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RevealAnimation
pod 'SDWebImage', '4.2.3'
end
